apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-multi-env
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: staging
          - env: prod
  template:
    metadata:
      name: nginx-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/BBrucelee2002/argocd-applicationset-basic.git
        targetRevision: HEAD
        path: apps/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
